/**
 * Catálogo maestro de ítems por pestaña (section / group / precios por defecto).
 * Fuente de verdad cuando el HTML solo tiene contenedores vacíos.
 */

/** @type {Record<string, Array<{ id: string, section: string, group?: string, price?: string, price2?: string, mark?: string }>>} */
export const MENU_CATALOG = {
  "Comidas.csv": [
    { id: "pumpkin", section: "salads", mark: "*" },
    { id: "mediterranean", section: "salads", mark: "*" },
    { id: "nachos", section: "share" },
    { id: "hummus", section: "share" },
    { id: "provoleta", section: "share" },
    { id: "carrots", section: "share" },
    { id: "bravas", section: "share" },
    { id: "olives", section: "share" },
    { id: "empanadas", section: "share" },
    { id: "eggplant", section: "share" },
    { id: "colita", section: "grill", mark: "*" },
    { id: "entraña", section: "grill", mark: "*" },
    { id: "lomo", section: "grill", mark: "*" },
    { id: "ribeye", section: "grill", mark: "*" },
    { id: "napolitana", section: "milanese", mark: "*" },
    { id: "especial", section: "milanese", mark: "*" },
    { id: "caballo", section: "milanese", mark: "*" },
    { id: "provoloneBurger", section: "burgers" },
    { id: "picante", section: "burgers" },
    { id: "portobello", section: "burgers" },
    { id: "clasica", section: "burgers" },
    { id: "cheeseBacon", section: "burgers" },
    { id: "extraEgg", section: "burgers", group: "extras", price: "2,5" },
    { id: "extraBacon", section: "burgers", group: "extras", price: "2" },
    { id: "extraAvocado", section: "burgers", group: "extras", price: "3" },
    { id: "extraPickles", section: "burgers", group: "extras", price: "1" },
    { id: "extraCheese", section: "burgers", group: "extras", price: "1" },
    { id: "extraTomato", section: "burgers", group: "extras", price: "1" },
    { id: "club", section: "sandwiches" },
    { id: "roastbeef", section: "sandwiches" },
    { id: "veggie", section: "sandwiches" },
    { id: "choripan", section: "sandwiches" },
    { id: "cheesecake", section: "desserts" },
    { id: "tiramisu", section: "desserts" },
    { id: "tatin", section: "desserts", mark: "*" },
    { id: "brownie", section: "desserts", mark: "*" },
    { id: "icecream", section: "desserts" },
  ],
  "Cacho-Burgers.csv": [
    { id: "cb_fries", section: "fries", price: "3,9" },
    { id: "cb_fingers", section: "fries", price: "8,5" },
    { id: "cb_extra_xl", section: "fries", group: "extras", price: "1,5" },
    { id: "cb_extra_bacon", section: "fries", group: "extras", price: "1,5" },
    { id: "cb_extra_jalapeno", section: "fries", group: "extras", price: "2" },
    { id: "cb_extra_salsa", section: "fries", group: "extras", price: "1" },
    { id: "cb_cookie", section: "cookies", price: "4,5" },
    { id: "cb_cheese_bacon", section: "burgers", price: "7,9", price2: "12,5" },
    { id: "cb_clasica", section: "burgers", price: "8,5", price2: "13" },
    { id: "cb_hot_latina", section: "burgers", price: "9,2", price2: "13,6" },
    { id: "cb_pollo_frito", section: "burgers", price: "9,5" },
    { id: "cb_vegetariana", section: "burgers", price: "8,9" },
    { id: "cb_addon_meat", section: "addons", group: "extras", price: "3,9" },
    { id: "cb_addon_cheese", section: "addons", group: "extras", price: "1" },
    { id: "cb_kids", section: "kids", price: "10,9" },
    { id: "combo_addon", section: "combo", price: "4" },
  ],
  "Menu-Grupos.csv": [
    { id: "package_full", section: "full", price: "29" },
    { id: "gr_starter1", section: "full", group: "starter" },
    { id: "gr_starter2", section: "full", group: "starter" },
    { id: "gr_main1", section: "full", group: "main" },
    { id: "gr_main2", section: "full", group: "main" },
    { id: "gr_main3", section: "full", group: "main" },
    { id: "gr_main4", section: "full", group: "main" },
    { id: "gr_dessert1", section: "full", group: "dessert" },
    { id: "gr_dessert2", section: "full", group: "dessert" },
    { id: "gr_drink1", section: "full", group: "drink" },
    { id: "gr_drink2", section: "full", group: "drink" },
    { id: "gr_drink3", section: "full", group: "drink" },
    { id: "package_pica", section: "pica", price: "29" },
    { id: "gr_pp1", section: "pica", group: "food" },
    { id: "gr_pp2", section: "pica", group: "food" },
    { id: "gr_pp3", section: "pica", group: "food" },
    { id: "gr_pp4", section: "pica", group: "food" },
    { id: "gr_pp5", section: "pica", group: "food" },
    { id: "gr_pp6", section: "pica", group: "dessert" },
    { id: "gr_pp7", section: "pica", group: "dessert" },
    { id: "gr_pp8", section: "pica", group: "drink" },
    { id: "gr_pp9", section: "pica", group: "drink" },
    { id: "gr_pp10", section: "pica", group: "drink" },
  ],
};

/** Ítems de café (grupo coffee en HTML) */
export const COFFEE_MAIN_IDS = [
  "caramel",
  "classicLatte",
  "flatWhite",
  "latte",
  "matcha",
  "chai",
  "espresso",
];
